export const tools = [
  {
    slug: "youtube",
    title: "Tải Video YouTube",
    description:
      "Tải video YouTube chất lượng cao (1080p, 4K) — MP4 hoặc MP3 — hoàn toàn miễn phí.",
    icon: "▶",
    color: "bg-red-50 text-red-600",
    endpoint: "/api/download/youtube",
    features: [
      "Hỗ trợ 1080p, 4K",
      "Chuyển sang MP3",
      "Không cần đăng ký",
      "Tốc độ tải nhanh",
    ],
  },
  {
    slug: "tiktok",
    title: "Tải Video TikTok",
    description:
      "Lưu video TikTok không watermark — đơn giản, nhanh chóng, miễn phí.",
    icon: "♪",
    color: "bg-pink-50 text-pink-600",
    endpoint: "/api/download/tiktok",
    features: [
      "Không watermark",
      "Hỗ trợ video + ảnh",
      "Tải hàng loạt",
      "Tốc độ tối đa",
    ],
  },
  {
    slug: "facebook",
    title: "Tải Video Facebook",
    description: "Tải video Facebook, Reels, và story — công khai hoặc private.",
    icon: "f",
    color: "bg-blue-50 text-blue-600",
    endpoint: "/api/download/facebook",
    features: [
      "Hỗ trợ Reels",
      "Tải HD",
      "Không giới hạn",
      "Nhanh chóng",
    ],
  },
  {
    slug: "instagram",
    title: "Tải Video Instagram",
    description: "Tải video, reel, story từ Instagram — công khai hoặc private.",
    icon: "◉",
    color: "bg-purple-50 text-purple-600",
    endpoint: "/api/download/instagram",
    features: [
      "Reels & Stories",
      "Tải album ảnh",
      "HD Quality",
      "Miễn phí vĩnh viễn",
    ],
  },
];

export const pricingPlans = [
  {
    name: "Free",
    price: "0",
    period: "miễn phí",
    description: "Dành cho người dùng cá nhân",
    features: [
      "Tải video cơ bản",
      "Tối đa 10 tải/ngày",
      "Chất lượng 720p",
      "Có quảng cáo",
    ],
    cta: "Dùng miễn phí",
    popular: false,
  },
  {
    name: "Starter",
    price: "99.000",
    period: "VNĐ/tháng",
    description: "Dành cho cá nhân sử dụng thường xuyên",
    features: [
      "Tải không giới hạn",
      "Chất lượng 1080p",
      "Không quảng cáo",
      "Tích hợp API cơ bản",
      "Hỗ trợ email",
    ],
    cta: "Chọn Starter",
    popular: true,
  },
  {
    name: "Pro",
    price: "299.000",
    period: "VNĐ/tháng",
    description: "Dành cho creator và marketer",
    features: [
      "Mọi tính năng Starter",
      "Chất lượng 4K",
      "Tải hàng loạt (batch)",
      "API đầy đủ",
      "Dashboard quản lý",
      "Hỗ trợ ưu tiên",
    ],
    cta: "Chọn Pro",
    popular: false,
  },
  {
    name: "Enterprise",
    price: "Liên hệ",
    period: "",
    description: "Dành cho doanh nghiệp",
    features: [
      "Tất cả tính năng Pro",
      "Tùy chỉnh dashboard",
      "White-label",
      "SLA 99.9%",
      "Account manager riêng",
      "On-premise deployment",
    ],
    cta: "Liên hệ báo giá",
    popular: false,
  },
];

export const articles = [
  {
    slug: "cach-tai-video-youtube",
    title: "Cách tải video YouTube miễn phí — Hướng dẫn đầy đủ 2025",
    excerpt:
      "Tìm hiểu cách tải video YouTube dễ dàng, an toàn và miễn phí với ReviewPilot.",
    cover: null,
    category: "Hướng dẫn",
    date: "2025-05-28",
    views: 12340,
    featured: true,
  },
  {
    slug: "so-sanh-cong-cu-tai-video",
    title: "So sánh 5 công cụ tải video tốt nhất 2025",
    excerpt:
      "Đánh giá chi tiết các công cụ tải video YouTube, TikTok, Facebook — ưu/nhược điểm và giá cả.",
    cover: null,
    category: "Đánh giá",
    date: "2025-05-20",
    views: 8230,
    featured: false,
  },
  {
    slug: "kiem-tien-affiliate-shopee",
    title: "Kiếm tiền với Shopee Affiliate cho người mới bắt đầu",
    excerpt:
      "Hướng dẫn đăng ký Shopee Affiliate, tạo link và tối ưu thu nhập từ nền tảng Shopee.",
    cover: null,
    category: "Kiếm tiền online",
    date: "2025-05-15",
    views: 15670,
    featured: true,
  },
  {
    slug: "huong-dan-tai-tiktok-khong-watermark",
    title: "Hướng dẫn tải video TikTok không watermark miễn phí",
    excerpt:
      "Cách tải video TikTok không watermark trên điện thoại và máy tính — đơn giản chỉ 3 bước.",
    cover: null,
    category: "Hướng dẫn",
    date: "2025-05-10",
    views: 9800,
    featured: false,
  },
  {
    slug: "cach-tao-link-affiliate-hieu-qua",
    title: "Cách tạo link affiliate hiệu quả để tăng tỷ lệ chuyển đổi",
    excerpt:
      "Mẹo và chiến lược để tạo link affiliate thu hút, tăng CTR và doanh thu từ Shopee Affiliate.",
    cover: null,
    category: "Kiếm tiền online",
    date: "2025-05-05",
    views: 6540,
    featured: false,
  },
  {
    slug: "download-video-dong-phat-triet-pha",
    title: "Công nghệ tải video: Cách hoạt động và tương lai",
    excerpt:
      "Giải mã công nghệ đằng sau công cụ tải video và xu hướng tương lai.",
    cover: null,
    category: "Công nghệ",
    date: "2025-04-28",
    views: 4320,
    featured: false,
  },
];

export const shopeeProducts = [
  {
    id: "1",
    name: "Tai Nghe Bluetooth Pro Max",
    price: "299.000",
    originalPrice: "599.000",
    rating: 4.8,
    sold: 15420,
    image: "https://cf.shopee.vn/file/xxx1",
    link: "https://shopee.vn/product/1",
    shopId: "shop123",
    commission: 5.5,
    category: "Điện tử",
  },
  {
    id: "2",
    name: "Bàn Phím Cơ Gaming RGB",
    price: "890.000",
    originalPrice: "1.200.000",
    rating: 4.9,
    sold: 8930,
    image: "https://cf.shopee.vn/file/xxx2",
    link: "https://shopee.vn/product/2",
    shopId: "shop456",
    commission: 4.2,
    category: "Gaming",
  },
  {
    id: "3",
    name: "Đèn LED Trang Trí Phòng",
    price: "79.000",
    originalPrice: "150.000",
    rating: 4.6,
    sold: 32100,
    image: "https://cf.shopee.vn/file/xxx3",
    link: "https://shopee.vn/product/3",
    shopId: "shop789",
    commission: 6.0,
    category: "Nội thất",
  },
  {
    id: "4",
    name: "Ốp Lưng iPhone 15 Pro",
    price: "59.000",
    originalPrice: "120.000",
    rating: 4.5,
    sold: 45600,
    image: "https://cf.shopee.vn/file/xxx4",
    link: "https://shopee.vn/product/4",
    shopId: "shop101",
    commission: 3.8,
    category: "Phụ kiện",
  },
  {
    id: "5",
    name: "Sạc Dự Phòng 20000mAh",
    price: "350.000",
    originalPrice: "520.000",
    rating: 4.7,
    sold: 28900,
    image: "https://cf.shopee.vn/file/xxx5",
    link: "https://shopee.vn/product/5",
    shopId: "shop202",
    commission: 4.5,
    category: "Điện tử",
  },
  {
    id: "6",
    name: "Gối Ôm Cao Cấp",
    price: "199.000",
    originalPrice: "350.000",
    rating: 4.4,
    sold: 18700,
    image: "https://cf.shopee.vn/file/xxx6",
    link: "https://shopee.vn/product/6",
    shopId: "shop303",
    commission: 5.0,
    category: "Nhà cửa",
  },
];

export const metrics = {
  totalUsers: 52400,
  totalDownloads: 1280000,
  totalArticles: 24,
  uptime: "99.9%",
  avgResponseTime: "120ms",
};

export type Article = typeof articles[number];
export type ShopeeProduct = typeof shopeeProducts[number];
export type Tool = typeof tools[number];
